version: '3.3'

services:

  frontend:
    container_name: projetoL-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - export DOCKER_CLIENT_TIMEOUT=120
